export const TICKER_SEARCH = {
  SET: 'TICKER_SEARCH.SET',
  CLEAR: 'TICKER_SEARCH.CLEAR',
  REQUEST: 'TICKER_SEARCH.REQUEST'
};

export const CHART = {
  FETCH: {
    REQUEST: 'CHART.FETCH.REQUEST',
    SUCCESS: 'CHART.FETCH.SUCCESS',
    ERROR: 'CHART.FETCH.ERROR'
  },
  CLEAR_ERROR: 'CHART.CLEAR_ERROR'
};